
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace OmnicellTelemetryDataForML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            OmnicellTelemetryDataForML.ModelInput sampleData = new OmnicellTelemetryDataForML.ModelInput()
            {
                Client_Name = @"XYZ",
                Hardware_Item = @"DOOR",
                Cabinet_Address = @"Cab 1 Cell 1 Door 3",
                Operation = @"Open",
                Open_Date___Time = @"03-01-2016 08:01",
                Duration_Mins = 3F,
                Duration_Secs = 25F,
                Duration_in_Secs = 205F,
                Close_Date___Time = @"03-01-2016 08:05",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = OmnicellTelemetryDataForML.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Status with predicted Status from sample data...\n\n");


            Console.WriteLine($"Client_Name: {@"XYZ"}");
            Console.WriteLine($"Hardware_Item: {@"DOOR"}");
            Console.WriteLine($"Cabinet_Address: {@"Cab 1 Cell 1 Door 3"}");
            Console.WriteLine($"Operation: {@"Open"}");
            Console.WriteLine($"Open_Date___Time: {@"03-01-2016 08:01"}");
            Console.WriteLine($"Duration_Mins: {3F}");
            Console.WriteLine($"Duration_Secs: {25F}");
            Console.WriteLine($"Duration_in_Secs: {205F}");
            Console.WriteLine($"Close_Date___Time: {@"03-01-2016 08:05"}");
            Console.WriteLine($"Status: {1F}");


            Console.WriteLine($"\n\nPredicted Status: {predictionResult.PredictedLabel}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
